// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

using QFramework;

namespace ARBattle
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    using UniRx;
    
    public class GuidePanelData : QFramework.UIPanelData
    {
    }
    
    public partial class GuidePanel : QFramework.UIPanel
    {
        
        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException ();
        }
        
        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as GuidePanelData ?? new GuidePanelData();
            // please add init code here
            //StageSystem.Instance.GuideStep.Select(step => "step : " + step).SubscribeToText(StepTxt).AddTo(this);        
        }
        


        protected override void OnOpen(QFramework.IUIData uiData)
        {
            Step1.gameObject.SetActive(true);
            Step2.gameObject.SetActive(false);
        }

        public void NextStep()
        {
            Step1.gameObject.SetActive(false);
            Step2.gameObject.SetActive(true);
        }

        protected override void OnShow()
        {
        }
        
        protected override void OnHide()
        {
        }
        
        protected override void OnClose()
        {
        }
    }
}
