// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ARBattle
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class GuidePanel
    {
        
        public const string NAME = "GuidePanel";
        
        [SerializeField()]
        public Image Step1;
        
        [SerializeField()]
        public Image Step2;
        
        private GuidePanelData mPrivateData = null;
        
        public GuidePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new GuidePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            Step1 = null;
            Step2 = null;
            mData = null;
        }
    }
}
