// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Arworld_prefab
    {
        public const string BundleName = "arworld_prefab";
        public const string ARWORLD = "arworld";
    }
    public class Blue_effect3_prefab
    {
        public const string BundleName = "blue_effect3_prefab";
        public const string BLUE_EFFECT3 = "blue_effect3";
    }
    public class Blue_effect5_explosion_prefab
    {
        public const string BundleName = "blue_effect5_explosion_prefab";
        public const string BLUE_EFFECT5_EXPLOSION = "blue_effect5_explosion";
    }
    public class Bossa_prefab
    {
        public const string BundleName = "bossa_prefab";
        public const string BOSSA = "bossa";
    }
    public class Chongjibo_prefab
    {
        public const string BundleName = "chongjibo_prefab";
        public const string CHONGJIBO = "chongjibo";
    }
    public class Doubleeye_prefab
    {
        public const string BundleName = "doubleeye_prefab";
        public const string DOUBLEEYE = "doubleeye";
    }
    public class Easyar_startup_prefab
    {
        public const string BundleName = "easyar_startup_prefab";
        public const string EASYAR_STARTUP = "easyar_startup";
    }
    public class Fireexit_wav
    {
        public const string BundleName = "fireexit_wav";
        public const string FIREEXIT = "fireexit";
    }
    public class Fireexplosion2_wav
    {
        public const string BundleName = "fireexplosion2_wav";
        public const string FIREEXPLOSION2 = "fireexplosion2";
    }
    public class Gamemanager_prefab
    {
        public const string BundleName = "gamemanager_prefab";
        public const string GAMEMANAGER = "gamemanager";
    }
    public class Gamepanel_prefab
    {
        public const string BundleName = "gamepanel_prefab";
        public const string GAMEPANEL = "gamepanel";
    }
    public class Gameplayer_prefab
    {
        public const string BundleName = "gameplayer_prefab";
        public const string GAMEPLAYER = "gameplayer";
    }
    public class Guidepanel_prefab
    {
        public const string BundleName = "guidepanel_prefab";
        public const string GUIDEPANEL = "guidepanel";
    }
    public class Imagetarget_prefab
    {
        public const string BundleName = "imagetarget_prefab";
        public const string IMAGETARGET = "imagetarget";
    }
    public class Loginpanel_prefab
    {
        public const string BundleName = "loginpanel_prefab";
        public const string LOGINPANEL = "loginpanel";
    }
    public class Monstera_prefab
    {
        public const string BundleName = "monstera_prefab";
        public const string MONSTERA = "monstera";
    }
    public class Paoziren_prefab
    {
        public const string BundleName = "paoziren_prefab";
        public const string PAOZIREN = "paoziren";
    }
    public class Player_prefab
    {
        public const string BundleName = "player_prefab";
        public const string PLAYER = "player";
    }
    public class Playerinfopanel_prefab
    {
        public const string BundleName = "playerinfopanel_prefab";
        public const string PLAYERINFOPANEL = "playerinfopanel";
    }
    public class Pumpkin_prefab
    {
        public const string BundleName = "pumpkin_prefab";
        public const string PUMPKIN = "pumpkin";
        public const string PUMPKIN2 = "pumpkin2";
    }
    public class Sha_num_png
    {
        public const string BundleName = "sha_num_png";
        public const string SHA_NUM = "sha_num";
    }
    public class Shaimg_prefab
    {
        public const string BundleName = "shaimg_prefab";
        public const string SHAIMG = "shaimg";
    }
    public class Socketserver_prefab
    {
        public const string BundleName = "socketserver_prefab";
        public const string SOCKETSERVER = "socketserver";
    }
    public class Stage_json
    {
        public const string BundleName = "stage_json";
        public const string STAGE = "stage";
    }
    public class Testzombiea_prefab
    {
        public const string BundleName = "testzombiea_prefab";
        public const string TESTZOMBIEA = "testzombiea";
    }
    public class Testzombieb_prefab
    {
        public const string BundleName = "testzombieb_prefab";
        public const string TESTZOMBIEB = "testzombieb";
    }
    public class Timedown_mp3
    {
        public const string BundleName = "timedown_mp3";
        public const string TIMEDOWN = "timedown";
    }
    public class Toastpanel_prefab
    {
        public const string BundleName = "toastpanel_prefab";
        public const string TOASTPANEL = "toastpanel";
    }
    public class Unkapolyarta_prefab
    {
        public const string BundleName = "unkapolyarta_prefab";
        public const string UNKAPOLYARTA = "unkapolyarta";
    }
    public class Yellow_effect_prefab
    {
        public const string BundleName = "yellow_effect_prefab";
        public const string YELLOW_EFFECT = "yellow_effect";
    }
    public class Zombie_attack_1_wav
    {
        public const string BundleName = "zombie_attack_1_wav";
        public const string ZOMBIE_ATTACK_1 = "zombie_attack_1";
    }
    public class Zombie_attack_3_wav
    {
        public const string BundleName = "zombie_attack_3_wav";
        public const string ZOMBIE_ATTACK_3 = "zombie_attack_3";
    }
    public class Zombie_growl_2_wav
    {
        public const string BundleName = "zombie_growl_2_wav";
        public const string ZOMBIE_GROWL_2 = "zombie_growl_2";
    }
    public class Zombieb_prefab
    {
        public const string BundleName = "zombieb_prefab";
        public const string ZOMBIEB = "zombieb";
    }
    public class Zombiec_prefab
    {
        public const string BundleName = "zombiec_prefab";
        public const string ZOMBIEC = "zombiec";
    }
    public class Zombied_prefab
    {
        public const string BundleName = "zombied_prefab";
        public const string ZOMBIED = "zombied";
    }
    public class Zombiee_prefab
    {
        public const string BundleName = "zombiee_prefab";
        public const string ZOMBIEE = "zombiee";
    }
    public class Zombieguide_prefab
    {
        public const string BundleName = "zombieguide_prefab";
        public const string ZOMBIEGUIDE = "zombieguide";
    }
}
