// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ARBattle
{
    using UnityEngine;
    using UnityEngine.UI;
    using QFramework;

    public class GamePanelData : QFramework.UIPanelData
    {
    };

    public partial class GamePanel : QFramework.UIPanel
    {

        protected override void ProcessMsg(int eventId, QFramework.QMsg msg)
        {
            throw new System.NotImplementedException();
        }

        protected override void OnInit(QFramework.IUIData uiData)
        {
            mData = uiData as GamePanelData ?? new GamePanelData();

            RestartBtn.onClick.AddListener((() =>
            {
                GameManager.Instance.ReStartGame();
                RestartBtn.gameObject.SetActive(false);
            }));
            RestartBtn.gameObject.SetActive(false);
        }

        protected override void OnOpen(QFramework.IUIData uiData)
        {
        }

        protected override void OnShow()
        {
        }

        protected override void OnHide()
        {
        }

        protected override void OnClose()
        {
        }

        protected override void OnBeforeDestroy()
        {
            base.OnBeforeDestroy();
           EventCenter.RemoveListener(EventDefine.ReStartGame, ShowRestartBtn);
            EventCenter.RemoveListener(EventDefine.TargetFound, CloseToastPanel);
            EventCenter.RemoveListener(EventDefine.TargetLost, ShowToastPanel);
        }

        protected override void RegisterUIEvent()
        {
            EventCenter.AddListener(EventDefine.ReStartGame, ShowRestartBtn);
            EventCenter.AddListener(EventDefine.TargetFound, CloseToastPanel);
            EventCenter.AddListener(EventDefine.TargetLost, ShowToastPanel);
        }

        private void ShowRestartBtn()
        {
            //RestartBtn.gameObject.SetActive(true);
            GameManager.Instance.ReStartGame();
        }

        private void ShowToastPanel()
        {
            UIMgr.OpenPanel<ToastPanel>(UILevel.Toast);
        }

        private void CloseToastPanel()
        {
            UIMgr.ClosePanel<ToastPanel>();
        }
    }
}