// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ARBattle
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class GamePanel
    {
        
        public const string NAME = "GamePanel";
        
        [SerializeField()]
        public Button RestartBtn;
        
        private GamePanelData mPrivateData = null;
        
        public GamePanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new GamePanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            RestartBtn = null;
            mData = null;
        }
    }
}
