// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ARBattle
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine;
    using UnityEngine.UI;
    
    
    public partial class PlayerInfoPanel
    {
        
        public const string NAME = "PlayerInfoPanel";
        
        [SerializeField()]
        public Text HpTxt;
        
        private PlayerInfoPanelData mPrivateData = null;
        
        public PlayerInfoPanelData mData
        {
            get
            {
                return mPrivateData ?? (mPrivateData = new PlayerInfoPanelData());
            }
            set
            {
                mUIData = value;
                mPrivateData = value;
            }
        }
        
        protected override void ClearUIComponents()
        {
            HpTxt = null;
            mData = null;
        }
    }
}
