// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Arworld_prefab
    {
        public const string BundleName = "arworld_prefab";
        public const string ARWORLD = "arworld";
    }
    public class Blue_effect3_prefab
    {
        public const string BundleName = "blue_effect3_prefab";
        public const string BLUE_EFFECT3 = "blue_effect3";
    }
    public class Blue_effect5_explosion_prefab
    {
        public const string BundleName = "blue_effect5_explosion_prefab";
        public const string BLUE_EFFECT5_EXPLOSION = "blue_effect5_explosion";
    }
    public class Doubleeye_prefab
    {
        public const string BundleName = "doubleeye_prefab";
        public const string DOUBLEEYE = "doubleeye";
    }
    public class Easyar_startup_prefab
    {
        public const string BundleName = "easyar_startup_prefab";
        public const string EASYAR_STARTUP = "easyar_startup";
    }
    public class Fireexit_wav
    {
        public const string BundleName = "fireexit_wav";
        public const string FIREEXIT = "fireexit";
    }
    public class Fireexplosion2_wav
    {
        public const string BundleName = "fireexplosion2_wav";
        public const string FIREEXPLOSION2 = "fireexplosion2";
    }
    public class Gamemanager_prefab
    {
        public const string BundleName = "gamemanager_prefab";
        public const string GAMEMANAGER = "gamemanager";
    }
    public class Gamepanel_prefab
    {
        public const string BundleName = "gamepanel_prefab";
        public const string GAMEPANEL = "gamepanel";
    }
    public class Gameplayer_prefab
    {
        public const string BundleName = "gameplayer_prefab";
        public const string GAMEPLAYER = "gameplayer";
    }
    public class Imagetarget_prefab
    {
        public const string BundleName = "imagetarget_prefab";
        public const string IMAGETARGET = "imagetarget";
    }
    public class Loginpanel_prefab
    {
        public const string BundleName = "loginpanel_prefab";
        public const string LOGINPANEL = "loginpanel";
    }
    public class Monster_prefab
    {
        public const string BundleName = "monster_prefab";
        public const string MONSTER = "monster";
    }
    public class Monstera_prefab
    {
        public const string BundleName = "monstera_prefab";
        public const string MONSTERA = "monstera";
    }
    public class Player_prefab
    {
        public const string BundleName = "player_prefab";
        public const string PLAYER = "player";
    }
    public class Playerinfopanel_prefab
    {
        public const string BundleName = "playerinfopanel_prefab";
        public const string PLAYERINFOPANEL = "playerinfopanel";
    }
    public class Socketserver_prefab
    {
        public const string BundleName = "socketserver_prefab";
        public const string SOCKETSERVER = "socketserver";
    }
    public class Stage_json
    {
        public const string BundleName = "stage_json";
        public const string STAGE = "stage";
    }
    public class Testzombiea_prefab
    {
        public const string BundleName = "testzombiea_prefab";
        public const string TESTZOMBIEA = "testzombiea";
    }
    public class Testzombieb_prefab
    {
        public const string BundleName = "testzombieb_prefab";
        public const string TESTZOMBIEB = "testzombieb";
    }
    public class Toastpanel_prefab
    {
        public const string BundleName = "toastpanel_prefab";
        public const string TOASTPANEL = "toastpanel";
    }
    public class Unkapolyarta_prefab
    {
        public const string BundleName = "unkapolyarta_prefab";
        public const string UNKAPOLYARTA = "unkapolyarta";
    }
    public class Zombie_attack_1_wav
    {
        public const string BundleName = "zombie_attack_1_wav";
        public const string ZOMBIE_ATTACK_1 = "zombie_attack_1";
    }
    public class Zombie_attack_3_wav
    {
        public const string BundleName = "zombie_attack_3_wav";
        public const string ZOMBIE_ATTACK_3 = "zombie_attack_3";
    }
    public class Zombie_growl_2_wav
    {
        public const string BundleName = "zombie_growl_2_wav";
        public const string ZOMBIE_GROWL_2 = "zombie_growl_2";
    }
    public class Zombiea_prefab
    {
        public const string BundleName = "zombiea_prefab";
        public const string ZOMBIEA = "zombiea";
    }
    public class Zombieb_prefab
    {
        public const string BundleName = "zombieb_prefab";
        public const string ZOMBIEB = "zombieb";
    }
}
